before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: no50fD15KqQEtokoVkPEVF7gJnT6NrP9BqKsNaVJt/TiTcleyBrOPoBPrXnDwuwEw+vF319J+EOyjJudgw834iDAkqPgvnmV1TUiUx97X6mVRfh1RfgQjLPYPCwLPKyVHqlavKPk04T9iYz9kExdj+aoNCmEqi98ixl0rBNLaQaOzsyKgUlSH5nVIT6wUHb6udJhqRL7KcyQBZSnKDfLaOFtk6PKdVPhWL020dc06mUW7vGASO453dKrRJLUl4nWIbcl7HMq8Ut3p2cCzrZ2mLcyCuii5Ey1a9ZoJwi0QFtRJ1ayX05A7VrSt8gla0uc87/x1Cbwc0coQH5qejVppRscVCV0+WSUKoV2j8ZF/1m0/R32/vuKjbEbDBjhOj/4DvpIxUp+eqONdbdNmUpRWGLPpvoaPbVyYXHXR2+zuxH4B0dJ6TSTKUnWD1w+dcKqQZrd+zJrHFEABWIwQ+y/Ixdpc702f9sceoWvlOyFUN0UjGoTllNRgBlbABXy4j8+syU3NP3VPuoYt7SZYSqZs3iGg5eU6WyMNOJgnT2lrbY3XRiResoHg6uQDIL4ycfqwZT7tW4EcJ5sJaqmZ5t3S/h+gBX0bC8pLmovANeKYu806KXFbzBuStvOur/0SIbSMWMUCEdU4XfPQaYUDibt3xiUJERp/4Schr2Pu9ZVBZU= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
